version: "3.8"
services:

  goservices-user:
    build: "."
    container_name: goservices-user
    # image: naufalhakm/library-api-user:v2
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: library
    ports:
      - "8082:8082"  # REST API
      - "50052:50052"  # gRPC
    restart: always

networks:
  default:
    external:
      name: nginx-proxy