CREATE TABLE authors (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id INT UNIQUE NOT NULL, 
    bio TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
